CREATE TABLE arbitrage_opportunities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_name TEXT NOT NULL,
    category TEXT NOT NULL,
    polymarket_price NUMERIC NOT NULL,
    kalshi_price NUMERIC NOT NULL,
    spread NUMERIC NOT NULL,
    arbitrage_percentage NUMERIC NOT NULL,
    profit_percentage NUMERIC NOT NULL,
    optimal_bet_amount NUMERIC NOT NULL,
    expected_profit NUMERIC NOT NULL,
    confidence_level TEXT NOT NULL CHECK (confidence_level IN ('low',
    'medium',
    'high')),
    risk_assessment TEXT NOT NULL CHECK (risk_assessment IN ('low',
    'medium',
    'high')),
    polymarket_market_id TEXT,
    kalshi_market_id TEXT,
    detected_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active',
    'expired',
    'executed')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);